config/routes.rb
Rails.application.routes.draw do
  resources :words
  root 'words#index'
  get 'signin', to: 'user#signin'
  post 'signin', to: 'user#login'
  get 'register', to: 'user#new'
  post 'register', to: 'user#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  include BCrypt

  attr_reader :password, :password_confirmation
  has_many :words
  validates :full_name, :email, :password, presence: true, length: {minimum: 5, maximum: 30}
  validates :email, uniqueness: true
  validates :password, confirmation: true

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end


end

app/models/word.rb
class Word < ApplicationRecord
  validates :ru, :en, presence: true, length: { minimum: 3, maximum: 30 }
  validates :en, uniqueness: true
  validates :user_id, presence: true
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class User < ActiveRecord::Base
  def create
    @user = User.new(article_params)
    @user.password = params[:password]
    @user.save!
  end

  private
  def article_params
    params.require(:user).permit(:email, :full_name, :password, :password_conformation)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def new
    @words = Word.new
  end

  def create
    @words = Word.create(article_params)
    if @words.save
      redirect_to @words
    else
      render "new"
    end
  end

  def edit
    @words = Word.find(params[:id])
  end

  def update
    @words = Word.find(params[:id])
    if @words.update(article_params)
      redirect_to @words
    else
      render 'edit'
    end
  end

  def show
    @words = Word.find(params[:id])
  end

  def destroy
    @words = Word.find(params[:id])
    @words.destroy
    redirect_to words_path
  end

  private
  def article_params
    params.require(:word).permit(:ru, :en)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/word_helper.rb
module WordHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/words/edit.html.erb
<%= form_for @words, url: {action: "update"}, :method => :PUT do |form| %>
  <%= form.label :ru %>
  <%= form.text_field :ru %>
  <br>
  <%= form.label :en %>
  <%= form.text_field :en %>

  <%= form.submit %>

<% end %>

app/views/words/index.html.erb
<table border="1" width="100%">
  <thead>
  <tr>
    <th>EN</th>
    <th>RU</th>
  </tr>
  </thead>
  <tbody>
  <%= link_to "New", new_word_path(@words) %>
  <% @words.each do |word| %>
    <tr>
      <td><%= word.id %></td>
      <td><%= word.en %></td>
      <td><%= word.ru %></td>
      <td><%= link_to "Delete", {action: "destroy", id: word.id}, method: "delete" %></td>
      <td><%= link_to "Update", edit_word_path(word) %></td>
    </tr>
    <tr>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/words/show.html.erb
<%= form_for @words, url: {action: "edit"} do %>
  <%= @words.id%><br>
  <%= @words.en%><br>
  <%= @words.ru%>
<% end %>